name: public_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_bloc:
  flutter_svg:
  fluttertoast:
  loading_indicator: ^3.1.1
  go_router:
  shared_preferences:
  cached_network_image:
  image_picker:
  url_launcher:
  flutter_rating_bar: ^4.0.1
  group_button: ^5.3.4
  easy_localization: ^3.0.7
  share:
  flutter_launcher_icons: ^0.13.1
  intl_phone_field: ^3.2.0
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  country_pickers: ^3.0.1
  flutter_multi_formatter: ^2.12.8
  easy_rich_text: ^2.1.0
  google_places_flutter: ^2.0.8
  flutter_dotenv: ^5.1.0
  table_calendar: ^3.1.2
  flutter_timer_countdown: ^1.0.7
  barcode_widget: ^2.0.4
  mobkit_dashed_border: ^0.0.6
  flutter_masked_text2: ^0.9.1
  dropdown_button2: ^2.3.9
  fdottedline_nullsafety: ^2.0.1
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  timeago_flutter: ^3.7.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/mainLogo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/image/
    - assets/translations/
    - assets/font/
    - assets/lottie/
    - assets/image/user/
    - assets/image/bookTaxi/
    - assets/image/myBooking/
    - lib/Core/translations/utils/en.dart
    - lib/Core/translations/utils/fr.dart


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-ExtraBold.ttf
        - asset: assets/font/Poppins-Black.ttf
        - asset: assets/font/Poppins-BlackItalic.ttf
        - asset: assets/font/Poppins-ExtraBoldItalic.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-BoldItalic.ttf
        - asset: assets/font/Poppins-ExtraLight.ttf
        - asset: assets/font/Poppins-Light.ttf
        - asset: assets/font/Poppins-ExtraLightItalic.ttf
        - asset: assets/font/Poppins-Italic.ttf
        - asset: assets/font/Poppins-LightItalic.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-MediumItalic.ttf
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins-SemiBoldItalic.ttf
        - asset: assets/font/Poppins-Thin.ttf
        - asset: assets/font/Poppins-ThinItalic.ttf

